### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by unupingu** [8none1/thermostat#1]
Hy. I want to build your thermostat but when I run menu.py I get indentation error code = 400.I hope you can help me ,I'm not so good with programing.thanks

**Comment by 8none1** [comment]
This commit fixes the problem: https://github.com/8none1/thermostat/commit/b6b3d3d4d5c77b7d9b537d5abbad839bab838513

However - this project will require quite a lot of fiddling around to get working.  So be prepared to come across more and more problems.

**Comment by unupingu** [comment]
hy i am trying  to build again your thermostat but i have this error :no module named rsvg
i hope you have the patience to help me 
thanks.
