### ISSUE TITLE
rsvg error

### ISSUE THREAD

**Issue by unupingu** [8none1/thermostat#2]
hy i am trying to build again your thermostat but i have this error :no module named rsvg
i hope you have the patience to help me
thanks.

**Comment by 8none1** [comment]
You'll need to install python-rsvg

sudo apt-get install python-rsvg

**Comment by unupingu** [comment]
How about no module named Image

**Comment by 8none1** [comment]
Try installing python-imaging

If that doesn't work try Pillow:
https://www.raspberrypi.org/forums/viewtopic.php?f=32&t=95611

To reiterate, I don't think you're going to get on very well with this
script - it's not at all user friendly code. Good luck!
